code --install-extension 4ops.terraform --force &
code --install-extension ahebrank.yaml2json --force &
code --install-extension alexcvzz.vscode-sqlite --force &
code --install-extension atlassian.atlascode --force &
code --install-extension azurite.azurite --force &
code --install-extension christian-kohler.npm-intellisense --force &
code --install-extension christian-kohler.path-intellisense --force &
code --install-extension davidanson.vscode-markdownlint --force &
code --install-extension dbaeumer.vscode-eslint --force &
code --install-extension eeyore.yapf --force &
code --install-extension esbenp.prettier-vscode --force &
code --install-extension formulahendry.code-runner --force &
code --install-extension george-alisson.html-preview-vscode --force &
code --install-extension github.codespaces --force &
code --install-extension github.copilot --force &
code --install-extension github.copilot-chat --force &
code --install-extension github.remotehub --force &
code --install-extension github.vscode-github-actions --force &
code --install-extension github.vscode-pull-request-github --force &
code --install-extension golang.go --force &
code --install-extension grapecity.gc-excelviewer --force &
code --install-extension hbenl.vscode-test-explorer --force &
code --install-extension khaeransori.json2csv --force &
code --install-extension littlefoxteam.vscode-python-test-adapter --force &
code --install-extension mechatroner.rainbow-csv --force &
code --install-extension mohsen1.prettify-json --force &
code --install-extension ms-azuretools.azure-dev --force &
code --install-extension ms-azuretools.vscode-azure-github-copilot --force &
code --install-extension ms-azuretools.vscode-azureappservice --force &
code --install-extension ms-azuretools.vscode-azurefunctions --force &
code --install-extension ms-azuretools.vscode-azureresourcegroups --force &
code --install-extension ms-azuretools.vscode-cosmosdb --force &
code --install-extension ms-azuretools.vscode-docker --force &
code --install-extension ms-dotnettools.csdevkit --force &
code --install-extension ms-dotnettools.csharp --force &
code --install-extension ms-dotnettools.vscode-dotnet-runtime --force &
code --install-extension ms-dotnettools.vscodeintellicode-csharp --force &
code --install-extension ms-edgedevtools.vscode-edge-devtools --force &
code --install-extension ms-mssql.data-workspace-vscode --force &
code --install-extension ms-mssql.mssql --force &
code --install-extension ms-mssql.sql-bindings-vscode --force &
code --install-extension ms-mssql.sql-database-projects-vscode --force &
code --install-extension ms-ossdata.vscode-postgresql --force &
code --install-extension ms-python.autopep8 --force &
code --install-extension ms-python.black-formatter --force &
code --install-extension ms-python.debugpy --force &
code --install-extension ms-python.isort --force &
code --install-extension ms-python.python --force &
code --install-extension ms-python.vscode-pylance --force &
code --install-extension ms-toolsai.jupyter --force &
code --install-extension ms-toolsai.jupyter-keymap --force &
code --install-extension ms-toolsai.jupyter-renderers --force &
code --install-extension ms-toolsai.vscode-jupyter-cell-tags --force &
code --install-extension ms-toolsai.vscode-jupyter-slideshow --force &
code --install-extension ms-vscode-remote.remote-containers --force &
code --install-extension ms-vscode-remote.remote-ssh --force &
code --install-extension ms-vscode-remote.remote-ssh-edit --force &
code --install-extension ms-vscode-remote.remote-wsl --force &
code --install-extension ms-vscode.azure-repos --force &
code --install-extension ms-vscode.azurecli --force &
code --install-extension ms-vscode.powershell --force &
code --install-extension ms-vscode.remote-explorer --force &
code --install-extension ms-vscode.remote-repositories --force &
code --install-extension ms-vscode.test-adapter-converter --force &
code --install-extension ms-vsliveshare.vsliveshare --force &
code --install-extension numso.prettier-standard-vscode --force &
code --install-extension pushqrdx.inline-html --force &
code --install-extension pwabuilder.pwa-studio --force &
code --install-extension quicktype.quicktype --force &
code --install-extension qwtel.sqlite-viewer --force &
code --install-extension rangav.vscode-thunder-client --force &
code --install-extension redhat.java --force &
code --install-extension redhat.vscode-yaml --force &
code --install-extension ritwickdey.liveserver --force &
code --install-extension rvest.vs-code-prettier-eslint --force &
code --install-extension sharedo.sharedo-vscode-extension --force &
code --install-extension stoplight.spectral --force &
code --install-extension teabyii.ayu --force &
code --install-extension tomoki1207.pdf --force &
code --install-extension tuxtina.json2yaml --force &
code --install-extension unifiedjs.vscode-mdx --force &
code --install-extension visualstudioexptteam.intellicode-api-usage-examples --force &
code --install-extension visualstudioexptteam.vscodeintellicode --force &
code --install-extension vscjava.vscode-gradle --force &
code --install-extension vscjava.vscode-java-debug --force &
code --install-extension vscjava.vscode-java-dependency --force &
code --install-extension vscjava.vscode-java-pack --force &
code --install-extension vscjava.vscode-java-test --force &
code --install-extension vscjava.vscode-maven --force &
code --install-extension wholroyd.jinja --force
